source 'https://rubygems.org'

ruby '2.0.0'

gem 'newrelic_rpm'
gem 'sinatra'
gem 'shotgun'
gem 'capybara'
#gem 'data_mapper'
#gem 'bcrypt-ruby'
#gem 'dm-sqlite-adapter'
#gem 'database_cleaner'
gem 'rspec'
gem 'haml'
gem 'pony'
